artifactId=pub.lib.General_version.scheme.conversion.maven2gradle
contentsModel=self-contained
description=Conversion of Maven version requirements to Gradle version constraints.
documentation.generatedAt=2026-10-02T10:41:22Z
documentation.sourceCommit=54c010254ff49be3a02023d52f7bd59d2d347b36
documentation.sourceRef=main
gradleProjectPath=:version:scheme:conversion:maven2gradle
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.General_version.scheme.conversion.maven2gradle
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=version.scheme.conversion.maven2gradle
name=Maven to Gradle version conversion
path=version/scheme/conversion/maven2gradle
structureKind=artifact
technologyKinds=java
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
