artifactId=pub.lib.General_version.scheme.algites.v1
contentsModel=self-contained
description=Version 1 of the Algites ecosystem version scheme.
documentation.generatedAt=2026-09-28T07:03:49Z
documentation.sourceCommit=67ba981a36d49b7123c8939b82e12e2ee2846690
documentation.sourceRef=main
gradleProjectPath=:version:scheme:algites:v1
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.General_version.scheme.algites.v1
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=version.scheme.algites.v1
name=Algites version scheme v1
path=version/scheme/algites/v1
structureKind=artifact
technologyKinds=java
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
