artifactId=pub.lib.General_version.scheme.conversion.algites2maven.v1
contentsModel=self-contained
description=Conversion of Algites version scheme v1 to Maven version semantics.
documentation.generatedAt=2026-09-27T04:04:17Z
documentation.sourceCommit=1db22081d7c5d30b079a293334fc28d92878b330
documentation.sourceRef=main
gradleProjectPath=:version:scheme:conversion:algites2maven:v1
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.General_version.scheme.conversion.algites2maven.v1
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=version.scheme.conversion.algites2maven.v1
name=Algites v1 to Maven version conversion
path=version/scheme/conversion/algites2maven/v1
structureKind=artifact
technologyKinds=java
version.lane=1
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
